/**
 * FIDE federation codes with ISO 3166-1 alpha-2 codes for flag emoji generation.
 * Subdivision flags (England, Scotland, Wales) are hardcoded.
 */

function toFlag(iso2: string): string {
  return [...iso2.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join("");
}

interface Federation {
  code: string;
  name: string;
  flag: string;
}

function fed(code: string, name: string, iso2: string, flagOverride?: string): Federation {
  return { code, name, flag: flagOverride ?? toFlag(iso2) };
}

export const FEDERATIONS: Federation[] = [
  fed("AFG", "Afghanistan", "AF"),
  fed("ALB", "Albania", "AL"),
  fed("ALG", "Algeria", "DZ"),
  fed("AND", "Andorra", "AD"),
  fed("ANG", "Angola", "AO"),
  fed("ANT", "Antigua and Barbuda", "AG"),
  fed("ARG", "Argentina", "AR"),
  fed("ARM", "Armenia", "AM"),
  fed("ARU", "Aruba", "AW"),
  fed("AUS", "Australia", "AU"),
  fed("AUT", "Austria", "AT"),
  fed("AZE", "Azerbaijan", "AZ"),
  fed("BAH", "Bahamas", "BS"),
  fed("BRN", "Bahrain", "BH"),
  fed("BAN", "Bangladesh", "BD"),
  fed("BAR", "Barbados", "BB"),
  fed("BLR", "Belarus", "BY"),
  fed("BEL", "Belgium", "BE"),
  fed("BIZ", "Belize", "BZ"),
  fed("BEN", "Benin", "BJ"),
  fed("BER", "Bermuda", "BM"),
  fed("BOL", "Bolivia", "BO"),
  fed("BIH", "Bosnia and Herzegovina", "BA"),
  fed("BOT", "Botswana", "BW"),
  fed("BRA", "Brazil", "BR"),
  fed("IVB", "British Virgin Islands", "VG"),
  fed("BRU", "Brunei", "BN"),
  fed("BUL", "Bulgaria", "BG"),
  fed("BUR", "Burkina Faso", "BF"),
  fed("BDI", "Burundi", "BI"),
  fed("CAM", "Cambodia", "KH"),
  fed("CMR", "Cameroon", "CM"),
  fed("CAN", "Canada", "CA"),
  fed("CPV", "Cape Verde", "CV"),
  fed("CAF", "Central African Republic", "CF"),
  fed("CHI", "Chile", "CL"),
  fed("CHN", "China", "CN"),
  fed("COL", "Colombia", "CO"),
  fed("COM", "Comoros", "KM"),
  fed("CGO", "Congo", "CG"),
  fed("COD", "Congo (DR)", "CD"),
  fed("CRC", "Costa Rica", "CR"),
  fed("CRO", "Croatia", "HR"),
  fed("CUB", "Cuba", "CU"),
  fed("CYP", "Cyprus", "CY"),
  fed("CZE", "Czech Republic", "CZ"),
  fed("DEN", "Denmark", "DK"),
  fed("DJI", "Djibouti", "DJ"),
  fed("DOM", "Dominican Republic", "DO"),
  fed("ECU", "Ecuador", "EC"),
  fed("EGY", "Egypt", "EG"),
  fed("ESA", "El Salvador", "SV"),
  fed("ENG", "England", "GB", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
  fed("ERI", "Eritrea", "ER"),
  fed("EST", "Estonia", "EE"),
  fed("ETH", "Ethiopia", "ET"),
  fed("FAI", "Faroe Islands", "FO"),
  fed("FIJ", "Fiji", "FJ"),
  fed("FIN", "Finland", "FI"),
  fed("FRA", "France", "FR"),
  fed("GAB", "Gabon", "GA"),
  fed("GAM", "Gambia", "GM"),
  fed("GEO", "Georgia", "GE"),
  fed("GER", "Germany", "DE"),
  fed("GHA", "Ghana", "GH"),
  fed("GRE", "Greece", "GR"),
  fed("GUA", "Guatemala", "GT"),
  fed("GUI", "Guinea", "GN"),
  fed("GUY", "Guyana", "GY"),
  fed("HAI", "Haiti", "HT"),
  fed("HON", "Honduras", "HN"),
  fed("HKG", "Hong Kong", "HK"),
  fed("HUN", "Hungary", "HU"),
  fed("ISL", "Iceland", "IS"),
  fed("IND", "India", "IN"),
  fed("INA", "Indonesia", "ID"),
  fed("IRI", "Iran", "IR"),
  fed("IRQ", "Iraq", "IQ"),
  fed("IRL", "Ireland", "IE"),
  fed("ISR", "Israel", "IL"),
  fed("ITA", "Italy", "IT"),
  fed("JAM", "Jamaica", "JM"),
  fed("JPN", "Japan", "JP"),
  fed("JOR", "Jordan", "JO"),
  fed("KAZ", "Kazakhstan", "KZ"),
  fed("KEN", "Kenya", "KE"),
  fed("KOS", "Kosovo", "XK"),
  fed("KUW", "Kuwait", "KW"),
  fed("KGZ", "Kyrgyzstan", "KG"),
  fed("LAO", "Laos", "LA"),
  fed("LAT", "Latvia", "LV"),
  fed("LIB", "Lebanon", "LB"),
  fed("LES", "Lesotho", "LS"),
  fed("LBA", "Libya", "LY"),
  fed("LIE", "Liechtenstein", "LI"),
  fed("LTU", "Lithuania", "LT"),
  fed("LUX", "Luxembourg", "LU"),
  fed("MKD", "North Macedonia", "MK"),
  fed("MAD", "Madagascar", "MG"),
  fed("MAW", "Malawi", "MW"),
  fed("MAS", "Malaysia", "MY"),
  fed("MDV", "Maldives", "MV"),
  fed("MLI", "Mali", "ML"),
  fed("MLT", "Malta", "MT"),
  fed("MTN", "Mauritania", "MR"),
  fed("MRI", "Mauritius", "MU"),
  fed("MEX", "Mexico", "MX"),
  fed("MDA", "Moldova", "MD"),
  fed("MNG", "Mongolia", "MN"),
  fed("MNE", "Montenegro", "ME"),
  fed("MAR", "Morocco", "MA"),
  fed("MOZ", "Mozambique", "MZ"),
  fed("MYA", "Myanmar", "MM"),
  fed("NAM", "Namibia", "NA"),
  fed("NEP", "Nepal", "NP"),
  fed("NED", "Netherlands", "NL"),
  fed("NZL", "New Zealand", "NZ"),
  fed("NCA", "Nicaragua", "NI"),
  fed("NIG", "Niger", "NE"),
  fed("NGR", "Nigeria", "NG"),
  fed("NOR", "Norway", "NO"),
  fed("OMA", "Oman", "OM"),
  fed("PAK", "Pakistan", "PK"),
  fed("PLE", "Palestine", "PS"),
  fed("PAN", "Panama", "PA"),
  fed("PNG", "Papua New Guinea", "PG"),
  fed("PAR", "Paraguay", "PY"),
  fed("PER", "Peru", "PE"),
  fed("PHI", "Philippines", "PH"),
  fed("POL", "Poland", "PL"),
  fed("POR", "Portugal", "PT"),
  fed("PUR", "Puerto Rico", "PR"),
  fed("QAT", "Qatar", "QA"),
  fed("ROU", "Romania", "RO"),
  fed("RUS", "Russia", "RU"),
  fed("RWA", "Rwanda", "RW"),
  fed("SMR", "San Marino", "SM"),
  fed("STP", "São Tomé and Príncipe", "ST"),
  fed("SAU", "Saudi Arabia", "SA"),
  fed("SCO", "Scotland", "GB", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
  fed("SEN", "Senegal", "SN"),
  fed("SRB", "Serbia", "RS"),
  fed("SLE", "Sierra Leone", "SL"),
  fed("SGP", "Singapore", "SG"),
  fed("SVK", "Slovakia", "SK"),
  fed("SLO", "Slovenia", "SI"),
  fed("SOL", "Solomon Islands", "SB"),
  fed("SOM", "Somalia", "SO"),
  fed("RSA", "South Africa", "ZA"),
  fed("ESP", "Spain", "ES"),
  fed("SRI", "Sri Lanka", "LK"),
  fed("SUD", "Sudan", "SD"),
  fed("SUR", "Suriname", "SR"),
  fed("SWZ", "Eswatini", "SZ"),
  fed("SWE", "Sweden", "SE"),
  fed("SUI", "Switzerland", "CH"),
  fed("SYR", "Syria", "SY"),
  fed("TPE", "Chinese Taipei", "TW"),
  fed("TJK", "Tajikistan", "TJ"),
  fed("TAN", "Tanzania", "TZ"),
  fed("THA", "Thailand", "TH"),
  fed("TLS", "Timor-Leste", "TL"),
  fed("TOG", "Togo", "TG"),
  fed("TTO", "Trinidad and Tobago", "TT"),
  fed("TUN", "Tunisia", "TN"),
  fed("TUR", "Turkey", "TR"),
  fed("TKM", "Turkmenistan", "TM"),
  fed("UGA", "Uganda", "UG"),
  fed("UKR", "Ukraine", "UA"),
  fed("UAE", "United Arab Emirates", "AE"),
  fed("USA", "United States", "US"),
  fed("URU", "Uruguay", "UY"),
  fed("UZB", "Uzbekistan", "UZ"),
  fed("VEN", "Venezuela", "VE"),
  fed("VIE", "Vietnam", "VN"),
  fed("WLS", "Wales", "GB", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
  fed("YEM", "Yemen", "YE"),
  fed("ZAM", "Zambia", "ZM"),
  fed("ZIM", "Zimbabwe", "ZW"),
];
